---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dingtalk
    k8s-app: dingtalk
  name: dingtalk
  namespace: monitoring
spec:
  ports:
  - name: dingtalk
    port: 8060
    protocol: TCP
    targetPort: 8060
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dingtalk
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.0.1.64
  ports:
  - port: 8060
